# infrastructure/cloudformation-template.yml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApplicationStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/btg-bucket/template.yml
      Parameters:
        EnvironmentType: production
        InstanceType: t3.medium
        MinSize: 2
        MaxSize: 4

  MongoDBCluster:
    Type: AWS::DocDB::DBCluster
    Properties:
      MasterUsername: admin
      MasterUserPassword: !Ref MongoDBPassword
      DBClusterIdentifier: btg-cluster

Outputs:
  ApplicationURL:
    Description: "URL of the deployed application"
    Value: !GetAtt ApplicationStack.Outputs.ApplicationURL